#!/bin/bash
set -eu -o pipefail

git diff --word-diff-regex="[^[:space:]<>\"]+" "$1" "$2" | python -c "
from __future__ import print_function
import re
import sys
for line in sys.stdin:
  filtered_line = line.replace(\"--- a$1\", '.', 1).rstrip('\n') if line.startswith(\"--- \") else ''.join(re.findall(r\"\[-.+?-\]|{\+.+?\+}\", line))
  if filtered_line:
    print(filtered_line)
"
