#!/bin/bash
set -eu -o pipefail

git diff --word-diff-regex="[^[:space:]<>\"]+" "$1" "$2" | python << EOF
from __future__ import print_function
import re
import sys
for line in sys.stdin.readlines():
  if line.startswith("--- "):
    print(line.replace("--- a$2", '.', 1))
  elif "[-" in line or '{+' in line:
    print(''.join(re.findall(r"\[-.+?-\]|{\+.+?\+}", line)))
EOF
