#!/bin/bash
set -eu -o pipefail

git diff --word-diff-regex="[^[:space:]<>\"]+" "$1" "$2" | python -c "
from __future__ import print_function
import re
import sys
for line in sys.stdin:
  if re.match(r\"^(\+\+\+|---) \", line):
    print(line.rstrip('\n'))
  else:
    filtered_line = re.sub(r\"(data:image/.+?;).+?(\\\"|-\]|\+})\", r\"\1...\2\", '\n'.join(re.findall(r\"\[-.+?-\]|{\+.+?\+}\", line)))
    if filtered_line:
      print(filtered_line)
"
