#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

import glob
import sys

from lib import (
  generating,
  tuxapp,
)

main = \
  tuxapp.handle_exceptions(
  tuxapp.do(lambda *args, **kwargs: len(sys.argv[1:]) == 1 and tuxapp.is_existing_command('xdg-open') and tuxapp.call_process('xdg-open {} > /dev/null 2>&1 &'.format(tuxapp.quote_argument(generating.get_app_page_path(tuxapp.extract_app(sys.argv[1]))))))(
    lambda: \
      generating.generate_app_page(tuxapp.extract_app(sys.argv[1])) \
        if len(sys.argv[1:]) == 1 else \
      generating.generate_app_pages(tuxapp.extract_app(argument) for argument in sys.argv[1:] or glob.iglob(tuxapp.get_appfile_path('*'))) and \
      generating.generate_pages()
  ))

if __name__ == '__main__':
  main()
