#!/usr/bin/env bash
set -eu -o pipefail

if [[ ! $@ ]]; then
  readarray -t <<< $(
    find "${0%/*}"/lib -type f -name '*.py'
    grep -l -m 1 '^#!.*\bpython\b' --exclude-dir=* "${0%/*}"/*
  )
  set -- "${MAPFILE[@]}"
fi
exec pylint"${0##*[[:alpha:]]}" "$@"
