#!/bin/bash
set -eu -o pipefail

read -r -d '' script << EOF || :
from __future__ import print_function

def debug():
  import inspect
  import pdb
  import readline
  import rlcompleter

  def set_quit(self, *args, **kwargs):
    method(self, *args, **kwargs)
    self.quitting = 0
    readline.read_history_file(debug.history_path)
  method = pdb.Pdb.set_quit
  pdb.Pdb.set_quit = set_quit
  readline.write_history_file(debug.history_path)

  frame = inspect.currentframe().f_back
  pdb.Pdb.complete = rlcompleter.Completer(frame.f_locals).complete
  pdb.Pdb(completekey="\e[25~").set_trace(frame)

import readline
def main():
  import atexit
  import os
  import rlcompleter

  readline.set_history_length(10000)
  path = os.path.expanduser("~/.python_history")
  if os.path.exists(path):
    readline.read_history_file(path)
  setattr(debug, 'history_path', path)
  def write_history(path):
    try:
      readline.write_history_file(path)
    except IOError:
      pass
  atexit.register(write_history, path)

  __builtins__.debug = debug
  del globals()['main']
  reload()

def reload(*args, **kwargs):
  if args or kwargs:
    return __builtins__.reload(*args, **kwargs)
  else:
    import functools
    import imp
    import inspect
    import os

    def reloads(variables, variable):
      def decorator(function):
        @functools.wraps(function)
        def wrapper(*args, **kwargs):
          reload()
          return variables[variable](*args, **kwargs)
        return wrapper
      return decorator

    if len(inspect.stack()) <= 3:
      for path in "$@".split():
        mtime = os.path.getmtime(path)
        module = os.path.basename(path)
        setattr(reload, 'mtimes', getattr(reload, 'mtimes', {}))
        if mtime != reload.mtimes.get(module):
          reload.mtimes[module] = mtime
          variables = vars(imp.load_source(module, path))
          for variable, value in variables.items():
            if not variable.startswith('__'):
              globals()[variable] = reloads(variables, variable)(value) if hasattr(value, '__call__') else value

def timeit(*args, **kwargs):
  import timeit

  kwargs['number'] = 1
  return timeit.timeit(*args, **kwargs)

def trace(*args, **kwargs):
  import trace

  return trace.Trace().runfunc(*args, **kwargs)

main()
EOF
PYTHONSTARTUP=<(echo "$script") exec python
