#!/bin/bash
set -eu -o pipefail

diff_path=~/tuxapp.diff
html_path=/var/www/html

cd ~/tuxapp
git pull -q
./validate
./test
./parse
./generate
git diff --word-diff ./build "$html_path" > "$diff_path"
head -1000 "$diff_path"
rsync -a ./build/ "$html_path"
