#!/bin/bash
set -eu -o pipefail

diff_path=~/tuxapp.diff
root_path=/var/www/html

cd ~/tuxapp
git pull -q
./validate
./test
./parse
./generate
git diff --word-diff ./build "$root_path" > "$diff_path"
head -1000 "$diff_path"
rsync -a --delete ./build/ "$root_path"
