#!/bin/bash
set -eu -o pipefail

diff_path=~/tuxapp.diff
root_path=/var/www/html

function on-exit {
  local status=$?
  [[ $status == 0 ]] || echo "Exit status: $status" >&2
  exit $status
}
trap on-exit EXIT

cd ~/tuxapp
git pull -q
./validate
./test
./parse
./generate
git diff --word-diff ./build "$root_path" > "$diff_path"
head -1000 "$diff_path"
rsync -Oac --delete ./build/ "$root_path"
