#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

import glob
import sys

from lib import (
  tuxapp,
  validation,
)

main = \
  tuxapp.handle_exceptions(
    lambda: \
      validation.validate_appfile(tuxapp.extract_app(sys.argv[1])) \
        if len(sys.argv[1:]) == 1 else \
      validation.validate_appfiles(tuxapp.extract_app(argument) for argument in sys.argv[1:] or glob.iglob(tuxapp.get_appfile_path('*')))
  )

if __name__ == '__main__':
  main()
